- name: create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Recussively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creates app directory
  ansible.builtin.file:
    path: /app
    state: directory

# - name: "download {{component}} application"
#   ansible.builtin.get_url:
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: /tmp

# - name: "extract {{component}} application"
#   ansible.builtin.unarchive:
#     src: "/tmp/{{component}}.zip"
#     dest: /app
#     remote_src: yes
- name: Download artifact from nexus
  ansible.builtin.get_url:
    # url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    url: "http://172.31.41.220.137:8081/repository/catalogue/com/roboshop/catalogue//catalogue-1.2.0.zip"
    dest: /tmp

- name: "extract {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes